### ISSUE TITLE
Screen-13 does not compile

### ISSUE THREAD

**Issue by g-wizzy** [attackgoat/screen-13#66]
Hello !

I wanted to try your library for my project, and ran into the following error when attempting to build : 

```
error[E0599]: no associated item named `MESH_EXT` found for struct `ShaderStageFlags` in the current scope
   --> /home/g-wizzy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/screen-13-0.8.1/src/driver/shader.rs:407:41
    |
407 |         Self::new(vk::ShaderStageFlags::MESH_EXT, spirv)
    |                                         ^^^^^^^^ associated item not found in `ShaderStageFlags`

error[E0599]: no associated item named `TASK_EXT` found for struct `ShaderStageFlags` in the current scope
   --> /home/g-wizzy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/screen-13-0.8.1/src/driver/shader.rs:434:41
    |
434 |         Self::new(vk::ShaderStageFlags::TASK_EXT, spirv)
    |                                         ^^^^^^^^ associated item not found in `ShaderStageFlags`
```

I am new to Vulkan, and thought perhaps this has to do with my installation. Do you happen to know what went wrong ?

Thanks in advance and have a nice day !

**Comment by attackgoat** [comment]
This is caused by a bad `ash` reference in the `Cargo.toml` of v0.8.1 which is the current published version. A fix is in the `master` branch of this repo:

```toml
ash = ">=0.37.1"
```

For now the best path forward might be to use:

```
[dependencies]
screen-13 = { git = "https://github.com/attackgoat/screen-13.git" }
```

I am slowly working on v0.9 which includes a bunch of fixes and new features, there is a [CHANGELOG](https://github.com/attackgoat/screen-13/blob/master/CHANGELOG.md). Please open issues or discussions about anything the doesn't work or isn't clear/helpful.

**Comment by g-wizzy** [comment]
It works ! Thanks a lot. I'll make sure to open new issues should I run into any.

**Comment by attackgoat** [comment]
Finally closing this after pushing out v0.9 with a permanent fix
